---

dataset:
  path: "./data/{}.json"
  name: "nonFedFinDataset"

model:
  name: "Qwen/Qwen3-0.6B"
  quantization: 4 # 8 or 4 if you want to do quantization with BitsAndBytes
  gradient_checkpointing: True # ! Ensure it matches that in train.train_arguments
  use_fast_tokenizer: False
  lora:
    peft_lora_r: 16
    peft_lora_alpha: 64
    target_modules: ["q_proj","v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  rope_scaling:
    type: "yarn"
    factor: 4.0

train:
  save_every_round: 5
  seq_length: 131072
  padding_side: "left"
  training_arguments:
    learning_rate: 5e-6
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 1
    logging_steps: 10
    max_steps: 5
    save_steps: 200
    save_total_limit: 10
    gradient_checkpointing: True # ! Ensure it matches that in model
    lr_scheduler_type: "cosine"
